---

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

branches:
  only:
    - master
    - develop

install:
  - composer self-update
  - composer install --prefer-source

before_script:
  - mkdir -p build/coverage

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls

notifications:
  irc: "irc.freenode.org#matryoshka.dev"
  email:
    - ripaclub@gmail.com

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.4
    - php: 7
    - php: hhvm